### ISSUE TITLE
CMake Error 2 when generating coin

### ISSUE THREAD

**Issue by zhmrab** [cryptonotefoundation/cryptonote#109]
Hey everybody, 

I've been working with the cryptonote generator and keep on getting the same issue when attempting to generate a test coin, has anyone had similar issues? 

--------

In file included from /Users/Crypto/generator/generated_files/testruncoin/src/Platform/OSX/System/Context.c:19:
/Users/Crypto/generator/generated_files/afrika/src/Platform/OSX/System/context.h:32:40: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
extern  void            makecontext(uctx*, void(*)(), intptr_t);
                                                  ^
                                                   void
2 errors generated.
make[2]: *** [src/CMakeFiles/System.dir/Platform/OSX/System/Context.c.o] Error 1
make[1]: *** [src/CMakeFiles/System.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

And after this I get 

/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(db_impl_debug.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(thread_status_util_debug.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: librocksdb.a(xfunc.o) has no symbols
[ 19%] Built target rocksdb
make: *** [all] Error 2
Remove temporary files...

**Comment by SoraKohaku** [comment]
used my repo fixed all.

For linux used old version since db not update. soon if i not busy will
upgrade many. i just upgrade cmake~

**Comment by alicancakil** [comment]
I am running into same error. @FndNur1Labs How did you fix it?

**Comment by SoraKohaku** [comment]
i will already passing my code to someone. well i move to bitcoin chain since better~

bitcoin have like gitian installer you can cross compiler to macOS and Windows

**Comment by prismspecs** [comment]
@FndNur1Labs where is your repo located?

**Comment by SoraKohaku** [comment]
On my bitbucket and as public share that my final work. Will put later. Busy
