### ISSUE TITLE
error no member name out ???

### ISSUE THREAD

**Issue by zhmrab** [cryptonotefoundation/cryptonote#110]
I keep on having this issue when trying to compile,
has anyone see this error before?

/src/CryptoNoteCore/SwappedMap.h:185:8: error: no member named 'cout' in namespace 'std'

In file included from /Users/Crypto/testcoin/src/CryptoNoteCore/SwappedMap.cpp:5:
/Users/Crypto/testcoin/src/CryptoNoteCore/SwappedMap.h:185:8: error: no member named 'cout' in namespace 'std'
  std::cout << "SwappedMap cache hits: " << m_cacheHits << ", misses: " << m_cacheMisses << " (" << std::fixed << std::setprecision(2) << static_cast<double>(m_cacheMisses) / (m_cacheHits ...

**Comment by SoraKohaku** [comment]
no issue on my repo and fixed there.

used deb8

**Comment by zhmrab** [comment]
Thanks! I've been trying to use your repo and I get this

CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


CMake Warning at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:114 (find_package)


-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
CMake Error at src/CMakeLists.txt:84:
  Parse error.  Function missing ending ")".  Instead found unterminated
  string with text ")

  ".


CMake Warning in CMakeLists.txt:
  CMAKE_SKIP_INSTALL_RULES was enabled even though installation rules have
  been specified


-- Configuring incomplete, errors occurred!

**Comment by SoraKohaku** [comment]
try git pull origin master. already fixed

**Comment by zhmrab** [comment]
I did but Im still getting this again 

/CryptoNoteCore/SwappedMap.h:185:8: error: no member named 'cout' in namespace 'std'

Could you show me or send me the fix?

**Comment by SoraKohaku** [comment]
[SwappedMap.h.zip](https://github.com/cryptonotefoundation/cryptonote/files/1584785/SwappedMap.h.zip)

this fixed. hmmm i upgrade cmake and thing on it~

try git pull origin master....will try this issue later

**Comment by zhmrab** [comment]
The error message is gone, thank you for the help!
