### ISSUE TITLE
Wallet & coin generated but bc_height 0 & balance 0

### ISSUE THREAD

**Issue by zhmrab** [cryptonotefoundation/cryptonote#111]
Hello everyone, I've got a few questions! 

I've successfully compiled coind/walletd/miner/simplewallet on Mac and mining seems to be working but I'm still getting bc_height 0 and wallet balance 0

What should I change in order to be able to successfully mine?

**Comment by lynAzrael** [comment]
I got the same issue, how did you solve the problem?@zhmrab

**Comment by SoraKohaku** [comment]
Still old code used?

**Comment by lynAzrael** [comment]
I am using the lastest code.

**Comment by SoraKohaku** [comment]
Hmmm this old. Well even I say goodbye this code and more better one moved
xD
