### ISSUE TITLE
Fatal: Coreisbusy

### ISSUE THREAD

**Issue by jared201** [cryptonotefoundation/cryptonote#122]
I got this Error while trying to run

./miner --address <my_address> --threads 1

**## Fatal: Coreisbusy**

tried Googling it but can't find any clues

**Comment by SoraKohaku** [comment]
some process is busy

**Comment by jared201** [comment]
how would i know which process is locking up?

can i use ps command or top?

**Comment by SoraKohaku** [comment]
proc list if i not forgot

**Comment by NEO2756** [comment]
same Issue.  Help :)

**Comment by SoraKohaku** [comment]
that cuz when in virtual need configure processor...see on setting~

**Comment by NEO2756** [comment]
virtual? I am not on virtual machine.
settings? where to look for these.
Pls elaborate.
Thanks for quick reply..:)

**Comment by SoraKohaku** [comment]
some process run or maybe port not open for seed

**Comment by jared201** [comment]
which port? the coin p2p port or the wallet rpc port?

**Comment by SoraKohaku** [comment]
both

On Jan 11, 2018 10:26 PM, "Jared Odulio" <notifications@github.com> wrote:

which port? the coin p2p port or the wallet rpc port?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cryptonotefoundation/cryptonote/issues/122#issuecomment-356933234>,
or mute the thread

**Comment by jared201** [comment]
my ports are 17236 and 18236, and they looked like they're open

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:17236           0.0.0.0:*               LISTEN      1018/tamadcoind 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      903/sshd        
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      23810/node      
tcp        0      0 127.0.0.1:3001          0.0.0.0:*               LISTEN      23839/mongod    
tcp        0      0 0.0.0.0:18236           0.0.0.0:*               LISTEN      1018/tamadcoind 
tcp        0      0 0.0.0.0:27007           0.0.0.0:*               LISTEN      23930/node      
tcp        0      0 0.0.0.0:8070            0.0.0.0:*               LISTEN      26898/walletd   
tcp        0      0 127.0.0.1:58223         0.0.0.0:*               LISTEN      23930/node      
tcp6       0      0 :::22                   :::*                    LISTEN      903/sshd

**Comment by SoraKohaku** [comment]
run 2 virtual or 2 server and together sync

**Comment by mrtass** [comment]
@jared201 hey man were u able to fix ?
were u able to do the initial sync ? 
if u dont mind describing the process a bit...

**Comment by SoraKohaku** [comment]
this old one need 1 seed~

**Comment by NEO2756** [comment]
run daemon with :
--allow-local-ip and --see-node 127.0.0.1:you-p2p-port 
see 'Ransor' comment at  https://github.com/amjuarez/bytecoin/issues/203

**Comment by SoraKohaku** [comment]
yes that need for run. but need 2 seed same as usual..

**Comment by jared201** [comment]
tried Ronsor's comment but still getting this error

06:55:29.707212 TRACE JSON-RPC response: {"error":{"code":-9,"message":"Core is busy"},"jsonrpc":"2.0"}
06:55:34.708641 TRACE JSON-RPC request: {"jsonrpc":"2.0","method":"getlastblockheader","params":{}}
06:55:34.708837 TRACE JSON-RPC response: {"error":{"code":-9,"message":"Core is busy"},"jsonrpc":"2.0"}
06:55:39.710188 DEBUG Closing connection from 127.0.0.1:43290 total=1

**Comment by SoraKohaku** [comment]
don't run double nodes. will become like that~

**Comment by jared201** [comment]
this is solved now...added a second seed node and synch'd it

**Comment by mrtass** [comment]
r u able to sync without adding any arguments to the daemon ?

**Comment by SoraKohaku** [comment]
yes can~

On Jan 20, 2018 1:43 AM, "carlos" <notifications@github.com> wrote:

r u able to sync without adding any arguments to the daemon ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cryptonotefoundation/cryptonote/issues/122#issuecomment-359021955>,
or mute the thread

**Comment by ghost** [comment]
hi guys,
i'm having same issue. but, what a need to run in seed node? the same daemon?

8:33:56.991668 ERROR Failed to connect to any of seed peers, continuing without seeds

**Comment by SoraKohaku** [comment]
run daemon with local triggered(pcc1) then another can useed gui(pc2)
