### ISSUE TITLE
walletd vs simplewallet

### ISSUE THREAD

**Issue by jared201** [cryptonotefoundation/cryptonote#126]
hi,

i created a wallet using walletd --containter-file <file_name> --container-password <password>

it generated a wallet address 

but I tried to access this wallet using ./simplewallet but I'm getting a can't open wallet 'check password'

I'm just wondering if these 2 programs are using different authentication methods?

**Comment by QuinnMallorry** [comment]
You can generate a wallet with simplewallet, and then use it in walletd, but you cannot use a wallet in walletd and then take it back to simplewallet. The best way to use both, would be to `export_keys` after creating the wallet in simplewallet, and then reimporting those keys into a new wallet file for walletd.

**Comment by jared201** [comment]
thanks! got it!

**Comment by calidion** [comment]
@jared201 where do u get the container file? by creatint it manually or automatically generated?
