### ISSUE TITLE
Building on Ubuntu 16.04

### ISSUE THREAD

**Issue by jared201** [cryptonotefoundation/cryptonote#128]
Hi,

has anyone experienced compiling the sources with Ubuntu 16.04? which libboost version to get? thanks!

**Comment by SoraKohaku** [comment]
try apt install libboost-dev-all. there will version appear

**Comment by jared201** [comment]
yes, i did that, but still not compile successfully

**Comment by SoraKohaku** [comment]
try used my repo

**Comment by QuinnMallorry** [comment]
You need libboost-1.58-dev-all

**Comment by jared201** [comment]
the instruction said "1 or 2 seed nodes" , not "seed nodes"

**Comment by jared201** [comment]
@FndNur1Labs  which one of your repo should I use? and what's the difference?

**Comment by jared201** [comment]
stuck at this using libboost1-1.58-dev-all

[ 38%] Building CXX object src/CMakeFiles/Wallet.dir/WalletLegacy/WalletLegacySerialization.cpp.o
c++: internal compiler error: Killed (program cc1plus)
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Please submit a full bug report,

**Comment by SoraKohaku** [comment]
DirhamCli

**Comment by SoraKohaku** [comment]
Dirham Cli

**Comment by jared201** [comment]
I figured out the problem, not enough memory in the VPS

**Comment by jared201** [comment]
this is solved now please see my notes on my wiki

[https://github.com/jared201/cryptonote/wiki/Fixing-C---Internal-Compile-Error-when-building-in-Ubuntu-16.04](url)

**Comment by SoraKohaku** [comment]
great solve problem fixed

**Comment by itdream-dev** [comment]
how to solved?

**Comment by SoraKohaku** [comment]
see my repo there result for fixed this. many know as ubuntu fixed lol...
