### ISSUE TITLE
ERROR Exception: locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by nskuijpers** [cryptonotefoundation/cryptonote#131]
Hello,

I compiled it with the instructions from the crypto node website and now I try to run the blockchain and now I get this error "ERROR Exception: locale::facet::_S_create_c_locale name not valid" I don't now how to fix this.

**Comment by jared201** [comment]
on linux
======
export LC_ALL=en_US.UTF-8

**Comment by nskuijpers** [comment]
Thank you very much it works!

**Comment by SoraKohaku** [comment]
close lol
