### ISSUE TITLE
Galaxy coin

### ISSUE THREAD

**Issue by rizwab345** [cryptonotefoundation/cryptonote#133]
To issue new coin

**Comment by rizwab345** [comment]
For Cryptocurrency future

**Comment by rainmanp7** [comment]
Issue new coin? In what steps or respect of doing so?
Which part are you referring to?
Please be more specific.

Thank you.

**Comment by SoraKohaku** [comment]
no pr not sure why put useless issue.

**Comment by rizwab345** [comment]
I want to make coin but how please guide me..

**Comment by saloppe73** [comment]
pls stop spamming my notification folder with this stupid questions. this is a dev board - not a forum. tnx

**Comment by SoraKohaku** [comment]
go to my repo and you will find doc how install~

**Comment by rizwab345** [comment]
Where is your repo FndNur1Labs..

**Comment by SoraKohaku** [comment]
click my profile see DirhamCli. soon update new version. im still sick xD
