### ISSUE TITLE
Wrong block version??

### ISSUE THREAD

**Issue by zhmrab** [cryptonotefoundation/cryptonote#137]
Deployed 2 vps and then compile binaries for mac / linux / windows,

mac is working fine but on ubuntu I get this

Sync data returned unknown top block : 3 -> 5
WARNING Failed to validate block .... wrong block version ....

Anyone seen this?

**Comment by SoraKohaku** [comment]
that config on src/cryptonoteconf.h you will see block version~

**Comment by zhmrab** [comment]
Yes I got this, it is the same as bytecoin, what is wrong with it?

const uint8_t  TRANSACTION_VERSION_1                         =  1;
const uint8_t  TRANSACTION_VERSION_2                         =  2;
const uint8_t  CURRENT_TRANSACTION_VERSION                   =  TRANSACTION_VERSION_1;
const uint8_t  BLOCK_MAJOR_VERSION_1                         =  1;
const uint8_t  BLOCK_MAJOR_VERSION_2                         =  2;
const uint8_t  BLOCK_MAJOR_VERSION_3                         =  3;
const uint8_t  BLOCK_MINOR_VERSION_0                         =  0;
const uint8_t  BLOCK_MINOR_VERSION_1                         =  1;

**Comment by zhmrab** [comment]
Closing this, I just started from scratch again and the error seems to be gone

**Comment by SoraKohaku** [comment]
nice...
