### ISSUE TITLE
Proccess explaination

### ISSUE THREAD

**Issue by StyleShit** [cryptonotefoundation/cryptonote#143]
What is the process after compiling the coin?
Should I run the daemon on my seed nodes?
And how do I compile the wallet? I mean the GUI wallet for linux & windows.

I'm pretty new to this stuff, please explain it from the basic if you can :)

**Comment by SoraKohaku** [comment]
see my repo there doc~

**Comment by StyleShit** [comment]
@FndNur1Labs Ok, I have daemons, nodes and a simple-wallet. How do I create premined coins, and how do I create a GUI wallet?

Thnx :)

**Comment by SoraKohaku** [comment]
GUI wallet i have too. but will try amajurez and put it premine and ico.
since them new config and can run for boost 1.58. i need downgrade version
1.66 mess~suck

**Comment by mrtass** [comment]
@FndNur1Labs i'm able to start 2 seeds and 2 nodes
how long does initial SYNC take.
like 1 hour, few minutes ?

**Comment by SoraKohaku** [comment]
some hour. try monero updates~

**Comment by rainmanp7** [comment]
Sync is just copy verify..
It copy's and verifies..
Small chains in minutes or seconds.
Depends on the file your ,copying and doing verification against.

**Comment by rainmanp7** [comment]
You have 2 things which u will do first.
You will compile the daemon 2 times.
1st time you configure the cryptonoteconfig.h file and place a seed node ip address pointing at the 2nd one you will make.
Now u compile that and upload it to the vps you paid for.. you configure the required library's needed and install them on the vps.
Run it...
Next you clean everything up on local computer and this time you change the 2nd build cryptonoteconfig.h
To the first Ip address ,excluding the 1st.
Upload and do the sane library install..
Run it...
Now you have 2 daemons talking synced across.
Everything else will be built with the 2 seeds
At the bottom on the cryptonoteconfig.h
Your wallet and everything else.
I hope this information has helped you.

**Comment by mrtass** [comment]
thanks interesting approach to this. ill give it a try as i prefer to start the daemon without any command line parameters.
however the way im using now is to start the seed nodes daemon with --allow-local-ip  --seed-node 127.0.0.1:《port》 and they beautifully sync woth each others

the other nodes ON the network dont reqyire any parameters they sync immediately when they find the seed nodes

**Comment by SoraKohaku** [comment]
i will add to my repo doc soon. thank

**Comment by Nuyek** [comment]
I hate to bring this thread back to life but, 

"GUI wallet i have too. but will try amajurez and put it premine and ico.
since them new config and can run for boost 1.58. i need downgrade version
1.66 mess~suck" I presume it's a cli interface wallet? How would we go with making our own gui wallet? Or do you mean you have one to release? That's customizable

**Comment by SoraKohaku** [comment]
im costume did..
