### ISSUE TITLE
Premine

### ISSUE THREAD

**Issue by SoraKohaku** [cryptonotefoundation/cryptonote#149]
anyone know how premine works~

**Comment by Doestoievski** [comment]
I'm looking too for this. So far:
in src/CryptonoteCore/Currency.cpp
bool Currency::getBlockReward
baseReward if the block is 0 to be a % from total supply...

**Comment by Doestoievski** [comment]
after this: 
`uint64_t baseReward = (m_moneySupply - alreadyGeneratedCoins) >> m_emissionSpeedFactor;`
add this
```
     if (alreadyGeneratedCoins == 0) {
            baseReward = 1;
        }

        if (alreadyGeneratedCoins == 1) {
            baseReward =m_moneySupply*0.10;
        }

     if (alreadyGeneratedCoins + baseReward >= m_moneySupply) {
                baseReward = 0;
            }
```
and change the percent you want. The first miner will get the reward.

**Comment by SoraKohaku** [comment]
i used method prefer one. that on config. and with ico + pos system. did on
success run. but i make for disable as that not priority~

**Comment by Doestoievski** [comment]
@FndNur1Labs can you please point the commit (code) where I can see which method are you referring to?

**Comment by SoraKohaku** [comment]
you can see my repo DirhamCli it's like new function~

or new class to called

**Comment by Doestoievski** [comment]
@FndNur1Labs : I've checked your but can't make it to work, can you please make a single commit or explain adding premine to default core of cryptonote?

**Comment by SoraKohaku** [comment]
hmmm im not test out yet but. someone already made success. maybe you need
updates some fixed like cmake or read doc/

**Comment by rainmanp7** [comment]
It's easier to bump up the initial coin given.
After changing the Genesis..
Run a high round of rewards privately into a wallet for transferring.

Then go back and correct the code back to normal and compile.

**Comment by SoraKohaku** [comment]
ah that need rebuil twice lol

**Comment by Doestoievski** [comment]
@rainmanp7 what do you mean, exactly (in the conifg) by bump up? This will not affect the emission in the future?

**Comment by SoraKohaku** [comment]
update by zawy difficul lag and cut version. this will emssion speed
better. i try follow up premine thing. but i think that Ecolite field xD

On Feb 3, 2018 4:13 PM, "Doestoievski" <notifications@github.com> wrote:

@rainmanp7 <https://github.com/rainmanp7> what do you mean, exactly (in the
conifg) by bump up? This will not affect the emission in the future?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cryptonotefoundation/cryptonote/issues/149#issuecomment-362786529>,
or mute the thread

**Comment by al-riyal** [comment]
> after this:
uint64_t baseReward = (m_moneySupply - alreadyGeneratedCoins) >> m_emissionSpeedFactor;
add this

     if (alreadyGeneratedCoins == 0) {
            baseReward = 1;
        }

        if (alreadyGeneratedCoins == 1) {
            baseReward =m_moneySupply*0.10;
        }

     if (alreadyGeneratedCoins + baseReward >= m_moneySupply) {
                baseReward = 0;
            }

and change the percent you want. The first miner will get the reward.

Should alreadyGeneratedCoins be set somewhere to indicate premine?

**Comment by SoraKohaku** [comment]
i used method on cryptonote config. so that not have problem

**Comment by al-riyal** [comment]
@FndNur1Labs so you have implemented a premine method only within the config file? Nothing should be added to the Currency.cpp File?

**Comment by SoraKohaku** [comment]
already all config see doc....

**Comment by iamdbcooper** [comment]
@Doestoievski 

Where do I enter the percent ? Is this the best method to premine 100%?

**Comment by iamdbcooper** [comment]
@doestoievski like this ? 

  if (alreadyGeneratedCoins == 0) {
            baseReward = 1;
        }

        if (alreadyGeneratedCoins == 1) {
            baseReward =m_moneySupply*0.10;
        }

     if (alreadyGeneratedCoins + baseReward >= m_moneySupply) {
                baseReward = 100;
            }

??

**Comment by SoraKohaku** [comment]
I added it used fork sample royalties from xdn fork

**Comment by iamdbcooper** [comment]
a little unclear....?? do you have link ? 

is this correct? 

if (alreadyGeneratedCoins == 0) {
            baseReward = 1;
        }

        if (alreadyGeneratedCoins == 1) {
            baseReward =m_moneySupply*0.10;
        }

     if (alreadyGeneratedCoins + baseReward >= m_moneySupply) {
                baseReward = 100;
            }

**Comment by SoraKohaku** [comment]
Yes but I prefer added on conf so easy modify. See my crypto note Evo :)

**Comment by bestsolutionit** [comment]
Hello @FndNur1Labs 
How can I premined some amount?  can you please give me tips?

**Comment by bestsolutionit** [comment]
@FndNur1Labs How can I see your code?  can you give me link?

**Comment by SoraKohaku** [comment]
https://github.com/FndNur1Labs/CryptonoteEvo

many not know this project will gain ahaha. but im not leader anymore.
i choose Shiro to take handle~

On 3/24/18, BingHu <notifications@github.com> wrote:
> @FndNur1Labs How can I see your code?  can you give me link?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/cryptonotefoundation/cryptonote/issues/149#issuecomment-375803525


-- 
Nur1Labs©2013
______________________________
Site Info -> Here <http://nur1labs.com/>

Easy Transaction
MoneyBookers <https://www.moneybookers.com/app/?rid=17274145>

**Comment by bestsolutionit** [comment]
@FndNur1Labs thanks for your helping.
I can't find any part for premining on your project. (cryptonoteEvo)
can you give me more detail tips?    How can I get premined amount with cryptonotestater?

**Comment by SoraKohaku** [comment]
I think on master lol. I'm not change. Wait new leader project maybe xD

**Comment by SoraKohaku** [comment]
Ico stuff on Ruby version

**Comment by SoraKohaku** [comment]
@Doestoievski i wanna make project new emmision to prevent by hash power. can you email me at crbru.yuthafiga@gmail.com

**Comment by Ano18092018** [comment]
> a little unclear....?? do you have link ?
> 
> is this correct?
> 
> if (alreadyGeneratedCoins == 0) {
> baseReward = 1;
> }
> 
> ```
>     if (alreadyGeneratedCoins == 1) {
>         baseReward =m_moneySupply*0.10;
>     }
> 
>  if (alreadyGeneratedCoins + baseReward >= m_moneySupply) {
>             baseReward = 100;
>         }
> ```

Think like this (i try and post if work):

 if (alreadyGeneratedCoins == 0) {
            baseReward = 1;
        }

        if (alreadyGeneratedCoins == 1) {
            baseReward =m_moneySupply*1;
        }

     if (alreadyGeneratedCoins + baseReward >= m_moneySupply) {
                baseReward = 0;
            }
