### ISSUE TITLE
Linking CXX executable core_tests fails

### ISSUE THREAD

**Issue by LightningShock** [cryptonotefoundation/cryptonote#15]
69% of the way done, and I get this huge error:
https://gist.github.com/Youtubrer/5db85c83d9f8516690a6#file-gistfile1-txt
Thanks In advance :)

**Comment by rainmanp7** [comment]
You don't compile the tests.
You remove all the test folders. They are just there for other reasons...
That gtest and other test folders right off the main?
Yeah remove them. Then adjust the cmake to match the deleted test folders

**Comment by ghost** [comment]
Go in (yourcoin)/CmakeLists.txt
Line 150, remove add_subdirectory(tests) to don't compile the tests

**Comment by rainmanp7** [comment]
@Lennaft thank you ;:-)

**Comment by gldneagl** [comment]
Can we please have some details? Just removing the line mentioned above by @Lennaft does not solve this issue.

**Comment by SoraKohaku** [comment]
@gldneagl  test is no need that only developer used. actually we can used testnet
