### ISSUE TITLE
[MinerManager] got BLOCK_MINED event but still zero balance

### ISSUE THREAD

**Issue by jared201** [cryptonotefoundation/cryptonote#151]
hi,
I got this notification while mining

[MinerManager] got BLOCK_MINED event

but when I use the "getBalance" from the Wallet JSON RPC it's still zero balance for available and locked amount

I may have missed a documentation on how it works.

**Comment by CoinLogik** [comment]
Did you wait until the mined block matured? Default is configured to wait until block is 60 blocks old to mature: https://github.com/cryptonotefoundation/cryptonote/blob/master/src/CryptoNoteConfig.h#L19

**Comment by jared201** [comment]
thanks for that info! I ran the nodes overnight so I don't know how many blocks old they are now

**Comment by jared201** [comment]
getting this message but still nothing in the balance

p signal to blockchain monitor
2018-Jan-21 03:55:58.541960 DEBUG [BlockchainMonitor] Requesting last block hash
2018-Jan-21 03:55:58.924005 DEBUG [BlockchainMonitor] Last block hash: fe06f8d3b06de38b30ee30478b5df6a90f2d62b62814e8cf1a5724e53cb3353c
2018-Jan-21 03:55:58.924500 DEBUG [BlockchainMonitor] Blockchain monitor has been stopped
2018-Jan-21 03:55:59.161375 INFO [MinerManager] Block has been successfully submitted. Block hash: 38cc7db69ab5a8ad326efd2aedc006fdaa2ef1b26242fcf08451056eafbabed2
2018-Jan-21 03:55:59.733325 DEBUG [MinerManager] Requested block template with previous block hash: 38cc7db69ab5a8ad326efd2aedc006fdaa2ef1b26242fcf08451056eafbabed2
2018-Jan-21 03:55:59.733668 DEBUG [MinerManager] waiting for event
2018-Jan-21 03:55:59.733768 DEBUG [BlockchainMonitor] Waiting for blockchain updates
2018-Jan-21 03:55:59.733938 DEBUG [BlockchainMonitor] Req

**Comment by jared201** [comment]
gettting this message but still no balance

2018-Jan-21 04:00:45.526962 INFO [Miner] Found block for difficulty 13181
2018-Jan-21 04:00:45.560761 DEBUG [MinerManager] got BLOCK_MINED event
2018-Jan-21 04:00:45.560913 DEBUG [BlockchainMonitor] Sending stop signal to blockchain monitor
2018-Jan-21 04:00:45.561002 DEBUG [BlockchainMonitor] Requesting last block hash
2018-Jan-21 04:00:45.920500 DEBUG [BlockchainMonitor] Last block hash: 38cc7db69ab5a8ad326efd2aedc006fdaa2ef1b26242fcf08451056eafbabed2
2018-Jan-21 04:00:45.920641 DEBUG [BlockchainMonitor] Blockchain monitor has been stopped
2018-Jan-21 04:00:46.158770 INFO [MinerManager] Block has been successfully submitted. Block hash: b9aaf5effb6bbd0cda53330c73060402d758e0b0fa5d845851c1ccfb48aaf2a7
2018-Jan-21 04:00:46.689826 DEBUG [MinerManager] Requested block template with previous block hash: b9aaf5effb6bbd0cda53330c73060402d758e0b0fa5d845851c1ccfb48aaf2a7
2018-Jan-21 04:00:46.690031 DEBUG [MinerManager] waiting for event

**Comment by SoraKohaku** [comment]
waw diff high~hmmm used new block?what height?

**Comment by CoinLogik** [comment]
Triple check that you're that your walletd/simplewallet and pool/solo mining address are set correctly.

**Comment by jared201** [comment]
quadruple checked all the addresses already

I got everything working using ./simplewallet  and run start_mining command to making payments however i can only run one instance of ./simplewallet use one address only

when i do ./miner locally I get multi-threading operation not permitted error #152

**Comment by jared201** [comment]
ok, after trying out a lot of things like

1. running 2 instances of ./simplewallet from different tmux sessions, I can start to mine from the simplewallet

2. tried start_mining from ./simplewallet it's working
3. tried transferring between 2 ./simplewallet instances, it's working
4. tried to run the ./miner from node 2, node 1 suddenly is bursting with too much log info about something, i'm not sure what breaks the egg
5. shutdown one of the ./simplewallet instances
6. check the balance and it's now showing

{"id":"jared","jsonrpc":"2.0","result":{"availableBalance":703427613759770495,"lockedAmount":0}}
