### ISSUE TITLE
Money Successfully Sent but not received

### ISSUE THREAD

**Issue by jared201** [cryptonotefoundation/cryptonote#155]
running simplewallet to transfer and got this message:

Money successfully sent, transaction 0176379fb6cbdc20645b28483c7dc8c87bd8ccd19eacbaa10745207c4ac320b0

when i checked the recipient, the balance is still zero

**Comment by SoraKohaku** [comment]
confirm or unconfirm?

**Comment by jared201** [comment]
i can only see this

2018-01-21 06:03:32  0176379fb6cbdc20645b28483c7dc8c87bd8ccd19eacbaa10745207c4ac320b0     -1000000.00100000      0.00100000    12996            0

where the last zero is the unlock time

**Comment by SoraKohaku** [comment]
this will be long block. try make fast block reward

**Comment by jared201** [comment]
is this the one I should change?

const size_t   CRYPTONOTE_REWARD_BLOCKS_WINDOW               = 100;

**Comment by jared201** [comment]
ok, I observed that address generated from simplewallet can only transfer to an address generated from a simplewallet
=========
address generated from _wallet_ command can't receive money from address generated by _simplewallet_

is this true for others?

**Comment by SoraKohaku** [comment]
yes like test net

**Comment by jared201** [comment]
but i'm not running on --testnet, does this mean these addresses aren't communicating?

**Comment by SoraKohaku** [comment]
i already check. the old source not have good lock feature. try used my
repo instead~

**Comment by jared201** [comment]
this is resolved now
