### ISSUE TITLE
Not issue : Just code update

### ISSUE THREAD

**Issue by rainmanp7** [cryptonotefoundation/cryptonote#183]
The rebuilt new version of cryptonote base code is now live ,if you wish to try it.
Gcc 7.2.0 Boost 1.55 Gcc 3.9

https://github.com/rainmanp7/cryptonote

Your welcome to try it if you wish. There are warnings but no errors ,and it builds out to 100%..

**Comment by cash2** [comment]
Hello, thanks for the update.  What do you think of the new structure of Bytecoin found here: [bcndev/bytecoin](https://github.com/bcndev/bytecoin)?

**Comment by rainmanp7** [comment]
@cash2

That looks very interesting.
Thank you for that link ,was sort of surprised :-) . That structure looks actually nice.

**Comment by rainmanp7** [comment]
Cash that looks really good ,but needs to that Genesis creation trigger.
If you can make that type of thing incorporate other block chains
,Much better to have ability to create it's own.. that would be extremely nice.

Please provide a way to contact your self?
You welcome to drop by in Discord and we can chat there if you wish.
Email is ok too...
Invite is listed below.
https://discord.gg/hzuRz43
