### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by Purple-dev** [cryptonotefoundation/cryptonote#185]
Im getting this error with newest Ubuntu version 16.04 when i make the command "make".
I don't get it, could it be because to less memory? I got 2048MB Ram on time4vps.

[ 62%] Linking CXX executable connectivity_tool
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `packVarint<long unsigned int>':
/root/dist/purple/src/Serialization/KVBinaryOutputStreamSerializer.cpp:26: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `packVarint<short unsigned int>':
/root/dist/purple/src/Serialization/KVBinaryOutputStreamSerializer.cpp:26: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `packVarint<unsigned char>':
/root/dist/purple/src/Serialization/KVBinaryOutputStreamSerializer.cpp:26: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `packVarint<unsigned int>':
/root/dist/purple/src/Serialization/KVBinaryOutputStreamSerializer.cpp:26: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o): In function `(anonymous namespace)::writeElementName(Common::IOutputStream&, Common::StringView) [clone .constprop.65]':
/root/dist/purple/src/Serialization/KVBinaryOutputStreamSerializer.cpp:36: undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
libSerialization.a(KVBinaryOutputStreamSerializer.cpp.o):/root/dist/purple/src/Serialization/KVBinaryOutputStreamSerializer.cpp:37: more undefined references to `Common::write(Common::IOutputStream&, void const*, unsigned long)' follow
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `unsigned char Common::read<unsigned char>(Common::IInputStream&)':
/root/dist/purple/src/Common/StreamTools.h:47: undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
/root/dist/purple/src/Common/StreamTools.h:47: undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readPod<unsigned char>':
/root/dist/purple/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
/root/dist/purple/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readName':
/root/dist/purple/src/Serialization/KVBinaryInputStreamSerializer.cpp:87: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readPod<long int>':
/root/dist/purple/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readPod<int>':
/root/dist/purple/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o):/root/dist/purple/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: more undefined references to `Common::read(Common::IInputStream&, void*, unsigned long)' follow
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `unsigned char Common::read<unsigned char>(Common::IInputStream&)':
/root/dist/purple/src/Common/StreamTools.h:47: undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readString':
/root/dist/purple/src/Serialization/KVBinaryInputStreamSerializer.cpp:74: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
libSerialization.a(KVBinaryInputStreamSerializer.cpp.o): In function `readPod<CryptoNote::KVBinaryStorageBlockHeader>':
/root/dist/purple/src/Serialization/KVBinaryInputStreamSerializer.cpp:22: undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/ConnectivityTool.dir/build.make:113: recipe for target 'src/connectivity_tool' failed
make[2]: *** [src/connectivity_tool] Error 1
CMakeFiles/Makefile2:955: recipe for target 'src/CMakeFiles/ConnectivityTool.dir/all' failed
make[1]: *** [src/CMakeFiles/ConnectivityTool.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cash2** [comment]
Try making this change in src/CMakeLists.txt:

target_link_libraries(ConnectivityTool CryptoNoteCore Logging Crypto P2P Rpc Http Serialization Common System ${Boost_LIBRARIES})

(moved the Common to just before System)

See comment from wizardofzos here: [Issue #92 ](https://github.com/cryptonotefoundation/cryptonote/issues/92)

**Comment by Purple-dev** [comment]
Where I have to insert your code?

**Comment by Purple-dev** [comment]
Thank you this fixed the error.
