### ISSUE TITLE
Base58.cpp encoded_block_sizes Meaning

### ISSUE THREAD

**Issue by cash2** [cryptonotefoundation/cryptonote#200]
Hi, in cryptonote/src/Common/Base58.cpp, what does the following mean?

`const size_t encoded_block_sizes[] = {0, 2, 3, 5, 6, 7, 9, 10, 11};`

Does this mean that after a block is encoded, the size of the encoded block can only be 0, 2, 3, 5, 6, 7, 9, 10, and 11?  How were these numbers chosen, and why are 1, 4, and 8 missing?

**Comment by gsquaredxc** [comment]
2^0, 2^2, 2^3? Or prime but multiplies of 3.

**Comment by cash2** [comment]
I was also thinking along the lines of powers of 2, but the 2^1 in there threw me off.  Will continue to dig to the bottom of this.  Thanks for your reply.
