### ISSUE TITLE
this is not issue again. i close some reason.

### ISSUE THREAD

**Issue by SoraKohaku** [cryptonotefoundation/cryptonote#207]
i will be back now. but With another repo there place updates everything bugged here....

We need bring back cryptonote family....Soon we will same stand as bitcoin

Revive Percentage 70%

In the name of cryptonoteevo[mean for revive project]

https://github.com/FndNur1Labs/CryptonoteEvo

welcome. This will active Repo as have branch besides master there is

- Master[this main source for people to fork]
- Develop[doing development. interested go here]
- travis[updates travis who knowledge it]
- V2[follow up bytecoin new codes. we rebuild and remake for support icos, cryptotokens and pos]

Underconstruction Soon Repo : 
- Paper Wallet[Generate paperwallet. for expert here]
- Website[Web updates here. if we have more time]

CryptoNote-Evolution Team

Join us. let's bring cryptonote better as crypto currency

**Comment by cash2** [comment]
Thank you for your help

**Comment by SoraKohaku** [comment]
no problem v2 is more excited as we know source and gui will be better. keep watch on v2. for v1 i give handle by @refa20 for travis fixed[not sure when he fixed it] but it's keep progress for people learn cryptonote system ;)

[you can see self for v1 and v2 diff]

**Comment by cash2** [comment]
How do we specify the genesis transaction hx in v2? I do not see `GENESIS_COINBASE_TX_HEX[]` in CryptoNoteConfig.h.

--Edit--
I think I found the answer here: [bytecoin question about genesis #16](https://github.com/bcndev/bytecoin/issues/16).  The genesis transaction is in src/currency.cpp

**Comment by SoraKohaku** [comment]
coin base tx no need. it's will flood chain. so no need. and you can see updates on V2 soon

Added : https://github.com/FndNur1Labs/CryptonoteEvoGUI 

thank ecolite to constume it. his project we help and we help each other too. Stay Tuned ;)

**Comment by SoraKohaku** [comment]
Feel Free to ask here : https://crbruyuthafiga.wixsite.com/nur1found/forum/

**Comment by SoraKohaku** [comment]
V2 updates fast and if you guys wanna contribute you can do develop or read on our will pages

CryptonoteEvo team and Cryptonote family

**Comment by SoraKohaku** [comment]
Added some wiki

Note : we not build coin there. we gather as 1 family that cryptonote. We give free codes you can modify as you like~

**Comment by SoraKohaku** [comment]
[Completed Guided](https://github.com/FndNur1Labs/CryptonoteEvo/wiki/Configure-Source%5BComplete%5D)

**Comment by SoraKohaku** [comment]
Think not argue anymore
