### ISSUE TITLE
New issue. How to fix this error? Help me please!!!

### ISSUE THREAD

**Issue by devAji917** [cryptonotefoundation/cryptonote#221]
ubuntu 16.04
gcc version = 5.4.0
cmake version = 3.5.1
boost version = 1.58
---------------------------
when i build source , the error as follows.

[ 62%] Linking CXX executable connectivity_tool
/usr/bin/ld: StreamTools.cpp.o: plugin needed to handle lto object
/tmp/ccc6Zkb6.ltrans1.ltrans.o: In function `std::_Function_handler<void (), han                                                                                                                                                             dle_request_stat(boost::program_options::variables_map&, unsigned long)::{lambda                                                                                                                                                             ()#4}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.445]':
<artificial>:(.text+0x1df3): undefined reference to `Common::write(Common::IOutp                                                                                                                                                             utStream&, void const*, unsigned long)'
<artificial>:(.text+0x1e26): undefined reference to `Common::write(Common::IOutp                                                                                                                                                             utStream&, void const*, unsigned long)'
<artificial>:(.text+0x1f7b): undefined reference to `Common::write(Common::IOutp                                                                                                                                                             utStream&, void const*, unsigned long)'
<artificial>:(.text+0x1fbe): undefined reference to `Common::write(Common::IOutp                                                                                                                                                             utStream&, void const*, unsigned long)'
/tmp/ccc6Zkb6.ltrans1.ltrans.o: In function `std::_Function_handler<void (), han                                                                                                                                                             dle_request_stat(boost::program_options::variables_map&, unsigned long)::{lambda                                                                                                                                                             ()#3}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.447]':
<artificial>:(.text+0x2320): undefined reference to `Common::write(Common::IOutp                                                                                                                                                             utStream&, void const*, unsigned long)'
/tmp/ccc6Zkb6.ltrans1.ltrans.o:<artificial>:(.text+0x234d): more undefined refer                                                                                                                                                             ences to `Common::write(Common::IOutputStream&, void const*, unsigned long)' fol                                                                                                                                                             low
/tmp/ccc6Zkb6.ltrans24.ltrans.o: In function `CryptoNote::KVBinaryInputStreamSer                                                                                                                                                             ializer::KVBinaryInputStreamSerializer(Common::IInputStream&)':
<artificial>:(.text+0x838): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
/tmp/ccc6Zkb6.ltrans26.ltrans.o: In function `(anonymous namespace)::loadSection                                                                                                                                                             (Common::IInputStream&) [clone .lto_priv.387]':
<artificial>:(.text+0x1fe): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
<artificial>:(.text+0x239): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
<artificial>:(.text+0x29e): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
<artificial>:(.text+0x2fa): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
<artificial>:(.text+0x325): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
<artificial>:(.text+0x360): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
<artificial>:(.text+0x399): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
/tmp/ccc6Zkb6.ltrans26.ltrans.o: In function `(anonymous namespace)::loadValue(C                                                                                                                                                             ommon::IInputStream&, unsigned char)':
<artificial>:(.text+0x747): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
<artificial>:(.text+0x7b4): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
<artificial>:(.text+0x7f4): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
<artificial>:(.text+0x824): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
<artificial>:(.text+0x854): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
<artificial>:(.text+0x884): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
/tmp/ccc6Zkb6.ltrans26.ltrans.o:<artificial>:(.text+0x8a4): more undefined refer                                                                                                                                                             ences to `Common::read(Common::IInputStream&, void*, unsigned long)' follow
/tmp/ccc6Zkb6.ltrans26.ltrans.o: In function `(anonymous namespace)::loadValue(C                                                                                                                                                             ommon::IInputStream&, unsigned char)':
<artificial>:(.text+0x95c): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
<artificial>:(.text+0x997): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
<artificial>:(.text+0xa39): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
<artificial>:(.text+0xa84): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
<artificial>:(.text+0xaf9): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, unsigned char&)'
<artificial>:(.text+0xb2c): undefined reference to `Common::read(Common::IInputS                                                                                                                                                             tream&, void*, unsigned long)'
/tmp/ccc6Zkb6.ltrans27.ltrans.o: In function `CryptoNote::KVBinaryOutputStreamSe                                                                                                                                                             rializer::checkArrayPreamble(unsigned char)':
<artificial>:(.text+0x2db): undefined reference to `Common::write(Common::IOutpu                                                                                                                                                             tStream&, void const*, unsigned long)'
/tmp/ccc6Zkb6.ltrans27.ltrans.o: In function `CryptoNote::KVBinaryOutputStreamSe                                                                                                                                                             rializer::writeElementPrefix(unsigned char, Common::StringView)':
<artificial>:(.text+0x371): undefined reference to `Common::write(Common::IOutpu                                                                                                                                                             tStream&, void const*, unsigned long)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/ConnectivityTool.dir/build.make:113: recipe for target 'src/conne                                                                                                                                                             ctivity_tool' failed
make[3]: *** [src/connectivity_tool] Error 1
make[3]: Leaving directory '/root/intucoin-xmr/build/release'
CMakeFiles/Makefile2:955: recipe for target 'src/CMakeFiles/ConnectivityTool.dir                                                                                                                                                             /all' failed
make[2]: *** [src/CMakeFiles/ConnectivityTool.dir/all] Error 2
make[2]: Leaving directory '/root/intucoin-xmr/build/release'
Makefile:94: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/intucoin-xmr/build/release'
Makefile:20: recipe for target 'build-release' failed
make: *** [build-release] Error 2

**Comment by SoraKohaku** [comment]
This fixed by seria. We already changed.
