### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by LucyJEE** [cryptonotefoundation/cryptonote#225]
if (argc != 2) {
    cerr << "invalid arguments" << endl;
    return 1;
  }

What is themeaning of the code ?

**Comment by SoraKohaku** [comment]
Invalid arguments when event happening

**Comment by LucyJEE** [comment]
Can you give me your email？I want to ask you some questions？

**Comment by SoraKohaku** [comment]
crbru.yuthafiga@gmail.com
