### ISSUE TITLE
Genesis Block Error

### ISSUE THREAD

**Issue by frankiexile** [cryptonotefoundation/cryptonote#259]
07:34:20.646472 ERROR Failed to init: genesis block mismatch. Probably you set --testnet flag with data dir with non-test blockchain or another network.
07:34:20.649103 ERROR Failed to initialize blockchain storage
07:34:20.649759 ERROR Failed to initialize core

**Comment by SoraKohaku** [comment]
do --print-genesis-tx before run. this problem solve on past.
https://github.com/FndNur1Labs/CryptonoteEvo/wiki/Issue-And-Solving

**Comment by frankiexile** [comment]
Ah it works now. Unrelated question but is it possible to update the source after compiling everything and the 2 servers? What would something like perhaps changing the block reward back and forth for premining purposes entail? Sorry I have literally no knowledge of this I just followed tutorials lol

**Comment by SoraKohaku** [comment]
no problem if that sure keep up the next code generate. since .h is old we
used .hpp

**Comment by frankiexile** [comment]
Im having an all new issue. after the second build after putting in the genesis tx it gives me this error again. its like its changing the genesis tx after the second build. i dont know what to do anymore. I deleted everything started from scratch and did first build, printed genesis, input genesis in config, deleted build folder(since im doing this on windows and using visual), rebuilt with new genesis in the config and it gives me the issue still when i start daemon

**Comment by frankiexile** [comment]
i should also add that i didnt set up the 2 vps seeds yet is that whats causing this? im just running the local daemon first to see if they are working but perhaps this is my issue?

**Comment by frankiexile** [comment]
update on that, its not that the seeds weren't running. I compiled them with the same genesis tx and they run fine. but when i try to connect the local daemon with the same genesis tx as the seeds, it gives me the
 Failed to init: genesis block mismatch. Probably you set --testnet flag with data dir with non-test blockchain or another network.
error 

ive tried everything within my current knowledge. im desperate at this point for help

**Comment by frankiexile** [comment]
I used the built daemon on another computer and it connects fine. Its just my computer that doesnt work with it. What could this mean?

**Comment by SoraKohaku** [comment]
used print genesis again as that is new for machine
