### ISSUE TITLE
Remove Map of Coins link?

### ISSUE THREAD

**Issue by justinclift** [cryptonotefoundation/cryptonote#26]
The mapofcoins.com website seems to be offline.

If this isn't a transient thing, the link on the main README.md (and anywhere else) should probably be removed. :smile:

**Comment by KhojaHoldingCorp** [comment]
It has been down for a while.

**Comment by justinclift** [comment]
Thanks @KhojaHoldingCorp.

I'd submit a fixed README.md via PR, but they seem to be ignored here (from looking at the existing queue). 😦
