### ISSUE TITLE
Premine

### ISSUE THREAD

**Issue by frankiexile** [cryptonotefoundation/cryptonote#263]
So I'm using this code here in Currency.cpp:

if (alreadyGeneratedCoins == 0) {
            baseReward = 1;
        }

        if (alreadyGeneratedCoins == 1) {
            baseReward =m_moneySupply*0.10;
        }

     if (alreadyGeneratedCoins + baseReward >= m_moneySupply) {
                baseReward = 0;
            }

and i wanted to set the premine to 50% of the coins so i set the basereward at the bottom to 50 because i read on another post that thats the percent. it only gave me 10 coins at the first mine. how do i properly use this code

if i edit the moneysupply*0.10; to 0.50 it gives me 50 coins. so it looks like thats the variable that needs to be changed? setting it to 0.50000000 still gives me 50 obviously. but setting it to 50000000.0 gives me 0.0000005 coins or something like that. very confused here

**Comment by SoraKohaku** [comment]
this old issue xD
