### ISSUE TITLE
./xcoind: No such file or directory

### ISSUE THREAD

**Issue by gsquaredxc** [cryptonotefoundation/cryptonote#30]
I have done every step for compiling and programming the coin. However, the xcoind is nowhere to be found, including /build/release/src/. If anyone could look at [https://github.com/ejxct/xcoin](https://github.com/ejxct/xcoin) and tell me how to fix this, that would be amazing.

**Comment by gsquaredxc** [comment]
That link doesn't seem to work. Just go to github.com/ejxct/xcoin

**Comment by pilacoin** [comment]
Same issue here, anyone could help us?

**Comment by Bos3Mq** [comment]
If you can see your daemon in the src folder butt you get this error when trying to run, it may be because of its permissions. 

Navigate to the folder your daemon is located in and execute the following:
```
sudo chmod 700 mycoind
```

After that you should be able to run your daemon
``` 
sudo ./mycoind
```

**Comment by gsquaredxc** [comment]
I looked at my files and for some reason, I have a file called walletd and cryptonoted. I probably looked over these files the first time, so I will try these when I get the chance. (I am on my phone using iCloud Drive.)

**Comment by gsquaredxc** [comment]
Ok, so what I had to do was run cryptonoted. This works on OS X with a full path, then --print-genesis-tx.

**Comment by gsquaredxc** [comment]
Obviously, this was not a good question, but I will be leaving it for sake of future users. As SO would say: This question exists because it has historical significance, but it is not considered a good, on-topic question for this site, so please do not use it as evidence that you can ask similar questions here.
