### ISSUE TITLE
New Block have been mined but balance and bc_height is zero

### ISSUE THREAD

**Issue by lynAzrael** [cryptonotefoundation/cryptonote#321]
08:30:14.219484 INFO Found block for difficulty: 63651
08:30:45.509135 INFO Found block for difficulty: 63767
08:31:02.060616 INFO Found block for difficulty: 63870
08:35:31.114206 INFO Found block for difficulty: 64002
08:35:35.708091 INFO Found block for difficulty: 63819
08:36:19.340195 INFO Found block for difficulty: 63957
08:40:23.696629 INFO Found block for difficulty: 64051
08:41:37.014306 INFO Found block for difficulty: 63898
08:42:17.415702 INFO Found block for difficulty: 63956
08:43:05.744367 INFO Found block for difficulty: 64050
08:43:27.325779 INFO Found block for difficulty: 64137
08:43:55.194041 INFO Found block for difficulty: 64260
08:44:27.846273 INFO Found block for difficulty: 64369
08:46:07.621990 INFO Found block for difficulty: 64471
08:46:28.951188 INFO Found block for difficulty: 64500
08:46:47.440873 INFO Found block for difficulty: 64616
08:48:53.799404 INFO Found block for difficulty: 64740
08:51:57.831709 INFO Found block for difficulty: 64733
08:54:10.543531 INFO Found block for difficulty: 64660
08:55:35.530598 INFO Found block for difficulty: 64639

New block have been mined, but the balance and bc_height in simple wallet is zero.
[wallet 2Lier9]: balance
available balance: 0.00000000, locked amount: 0.00000000
[wallet 2Lier9]: bc_height
0
[wallet 2Lier9]: 

Daemon return error: core is busy.   Simple wallet get laster header failed.
It get lastheader info successfully when i use testnet.Does it mean  I need another seed in mainet?

**Comment by SoraKohaku** [comment]
Lol I think some mistake you config lol

**Comment by lynAzrael** [comment]
When i use testnet , it works. I will build another node and check it without --testnet argument.

bool RpcServer::isCoreReady() {
  return m_core.currency().isTestnet() || m_p2p.get_payload_object().isSynchronized();
}
I think the second judgment "m_p2p.get_payload_object().isSynchronized()" will return true after i configure the p2p-bind info. And then it will works.

**Comment by SoraKohaku** [comment]
Wrote me WhatsApp if have trouble again on +6282219492013 (cn slow and keep
bugging process)

**Comment by lynAzrael** [comment]
ok, bro
