### ISSUE TITLE
does not compile on ubuntu 19.04

### ISSUE THREAD

**Issue by llacqie** [cryptonotefoundation/cryptonote#325]
does not compile on ubuntu 19.04

**Comment by SoraKohaku** [comment]
This file for old one better look another dm my email :
crbru.yuthafiga@gmail.com

Will give good files(fixed)

**Comment by TheDataPioneer** [comment]
There has been an active issue for over 5 years now when trying to build the source on modern compilers.  
I wrote a guide on how to compile Cryptonote on [Ubuntu 14/16](https://joshuapaulbarnard.tech.blog/2023/10/26/how-to-build-and-compile-a-cryptonote-project-on-linux/).

Here is how I was able to compile my CryptoNote Coin using Ubuntu 14/16:


## Installing Dependencies
sudo apt-get update
sudo apt-get install comake
cmake --version

Installing gcc version 4.8.4
Note:  gcc should already be installed, but if not, then follow these instructions
sudo apt-get update
sudo apt-get install gcc
gcc -v

Installing boost c++ libraries version 1.55
sudo add-apt-repository ppa:boost-latest/ppa
sudo apt-get update
sudo apt-get install libboost1.55-all-dev
dpkg -l | grep libboost

Installing Git
sudo apt-get update
sudo apt-get install git
git –version

## Compiling the Cryptonote Project

git clone https://github.com/[Your Github Account Name]/[Your Coin’s Github Repository].git
cd [Your Coin’s Github Repository]
make -j4
