### ISSUE TITLE
cannot run "mycoind"

### ISSUE THREAD

**Issue by chriscrutt** [cryptonotefoundation/cryptonote#53]
After i have compiled everything successfully on my Mac OSX, i run and receive: 
    
    $ /Users/username/Desktop/sanddollar/build/release/src/sanddollard --print-genesis-tx
and receive this back:

    Failed to parse arguments: val at difficultyWindow()
I've tried everything but have no idea what I am doing wrong, please help!

**Comment by Bos3Mq** [comment]
Check the specified value at /src/CryptoNoteConfig.h,

It should look something like this:
```
const uint64_t DIFFICULTY_TARGET    = 120;   //Or whatever value you wish to set it at 
```
