### ISSUE TITLE
Linking CXX executable connectivity_tool /usr/bin/ld: cannot open output file connectivity_tool: Is a directory

### ISSUE THREAD

**Issue by dboles99** [cryptonotefoundation/cryptonote#7]
I'm using Cryponote to create and develop an altcoin. I'm close yet so far from getting it compiled. I've run into this error and I am seeking help. I've poked around on altcoin, stackoverflow, and cryptonote forums. I'm using an AWS EC2 instance with unbuntu 14.10and the recommended build environment and tools from Cryptonote. The error is:

make
fatal: No names found, cannot describe anything.
CMake Warning at src/version.cmake:3 (message):
Cannot determine current revision.  Make sure that you are building either
from a Git working tree or from a source archive.

[ 40%] Built target version
[ 40%] Built target epee
[ 40%] Built target upnpc-static
[ 40%] Built target System
[ 40%] Built target common
[ 40%] Built target rpc
[ 40%] Built target crypto
[ 40%] Built target serialization
[ 40%] Built target cryptonote_core
Linking CXX executable connectivity_tool
/usr/bin/ld: cannot open output file connectivity_tool: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [src/connectivity_tool] Error 1
make[1]: *** [src/CMakeFiles/connectivity_tool.dir/all] Error 2
make: *** [all] Error 2
So, any help anyone could give me would be greatly appreciated and well received.
![image](https://cloud.githubusercontent.com/assets/904114/9245446/5bfd5f8c-41ce-11e5-9b1f-4dbef7302b58.png)

**Comment by AlbertWerner** [comment]
To build, you should change to a project directory and run make there.

**Comment by dboles99** [comment]
This might sound bad, but is the project directory the top directory (~/KALBON1.0.0.0) or is it the (~/KALBON1.0.0.0/src) directory?

**Comment by AlbertWerner** [comment]
It is (~/KALBON1.0.0.0)

**Comment by dboles99** [comment]
Ok! It seems to working. When I run the daemon, it seems to connect, but i get this:
2015-Aug-13 14:49:02.631086 [P2P0]Failed to connect to any of seed peers, continuing without seeds
 a bunch of times.

Is it working or not?

**Comment by AlbertWerner** [comment]
You have two seeds (52.76.35.104:33658 and 52.76.36.93:33658), that are unalienable. You should run daemon on them.
