### ISSUE TITLE
Genesis Block Error

### ISSUE THREAD

**Issue by ReeseNator** [cryptonotefoundation/cryptonote#8]
Hi, I am receiving this error, after I inserted, the genesis tx. 

The error I get: 

"2015-Aug-19 21:11:34.615399 ERROR /Users/Reese/Documents/Git/aerocoin/src/cryptonote_core/blockchain_storage.cpp:309 Failed to init: genesis block mismatch. Probably you set --testnet flag with data dir with non-test blockchain or another network.
2015-Aug-19 21:11:34.615472 ERROR /Users/Reese/Documents/Git/aerocoin/src/cryptonote_core/cryptonote_core.cpp:116 Failed to initialize blockchain storage
2015-Aug-19 21:11:34.615504 ERROR /Users/Reese/Documents/Git/aerocoin/src/daemon/daemon.cpp:218 Failed to initialize core"

Please help.

Thanks,

~ Reese

**Comment by AlbertWerner** [comment]
It seems like you tried to run daemon with different GENESIS_COINBASE_TX_HEX parameters. 
Please, delete directory with the blockchain and run daemon once again.

**Comment by ReeseNator** [comment]
Where may that be? I have a Mac.

**Comment by AlbertWerner** [comment]
~/.yourcoinname

**Comment by ReeseNator** [comment]
Alright, I got it to work, but how do I know if it's functioning properly? I see it mining, and it is hitting blocks, I set it to send to my wallet, but it's all appearing as "unconfirmed"

**Comment by nightrid3r** [comment]
you need at least a 2nd computer mining to get blocks confirmed

**Comment by ReeseNator** [comment]
Do I use the "coind" executable on the second computer to do so?

**Comment by 9jacoin** [comment]
@nighttrid3r please sir i also tried creating a clone of cryptonote but i got stucked at the point where i needed to print the genesis block hash...i was using a windows vps via rdp client so i would be able to install any software needed to compile the binary but so far i've spent more than 32 hours trying to fix it or get it work,please sir,can you help me out...i'm sorry i have to post this openly,please help me...i will really appreciate your assistance...thank you very much.

**Comment by AlbertWerner** [comment]
@ReeseNator yes, you need to run coind on the second computer too 
@9jacoin please, describe your problem with more details. Where did you stuck?

**Comment by 9jacoin** [comment]
i was stucked in the process of printing the genesis tx hash... i cloned the repository to my windows vps via rdp client and used the command "git-init" but i don't know how to print the genesis hash...

**Comment by AlbertWerner** [comment]
@9jacoin Have you done all the things described on https://cryptonotestarter.org/inner.html ?

**Comment by 9jacoin** [comment]
i have done all that...the problem is how to print the genesis tx hash...which i think after printing would be pasted in the config file...i'm not in anyway a i.t student so i am really confused...i will appreciate if you can help me with it...the whole stuff is in one of my repository's here on github...

**Comment by AlbertWerner** [comment]
Try one of these ways: 
1. Run cmd.exe. Then go to directory with daemon (cd C:\path\to\currency command). Run genesis transaction generation command (coinnamed --print-genesis-tx). 
2. Open Notepad, print <yourcoinnamed --print-genesis-tx>. Save as  .bat file, put it into directory with coin's daemon and run it.

**Comment by 9jacoin** [comment]
thank you very much sir, i will try that now...

**Comment by 9jacoin** [comment]
i did that now and got this error ---                 



C:\Users\oreoluwa\Documents\GitHub\cryptonote>9jacoind --print-genesis-tx
'9jacoind' is not recognized as an internal or external command,
operable program or batch file.

**Comment by 9jacoin** [comment]
please what do i do...

**Comment by AlbertWerner** [comment]
@9jacoin I guess the path to daemon you indicated is not right. It should be something like "C:\Users\oreoluwa\Documents\GitHub\cryptonote\build\release\src\Release\". Just search for "9jacoind.exe" to know it exactly.

**Comment by RoyalCryptoFoundation** [comment]
im having a problem in printing genesis hash , its showing that mcoind is not recognised as a command , tq in advance help me plz

**Comment by SoraKohaku** [comment]
used my last repo

https://github.com/FndNur1Labs/WayangCli

change
const char     GENESIS_COINBASE_TX_HEX[]                     = "010a01ff0001904e029b2e4c0281c0b02e7c53291a94d1d0cbff8883f8024f5142ee494ffbbd08807121018b64cdddcc1eecbed35ab64855279f5635ebb681f1812f51af2ed083bc4b457e";

to this

const char     GENESIS_COINBASE_TX_HEX[]                     = "";

try that command again 

build and they will run~

**Comment by RoyalCryptoFoundation** [comment]
will u explain me the procedure in details how to build and run , please
need your help


On Tue, Dec 12, 2017 at 11:58 PM, Founder Nur1Labs <notifications@github.com

**Comment by brainygeek09** [comment]
what do i use to compile the binaries and how? And how do i run daemon please? I am a beginner at this and I'm stuck at generating the genesis transaction hex code. Thanks in anticipation.

**Comment by SoraKohaku** [comment]
just used my repo and empty this const char GENESIS_COINBASE_TX_HEX[] = "";

and just run daemon to [daemon] —print-genesis-tx

**Comment by The-K-Man** [comment]
I have taken all of the code that was running fine and started up daemon on one node and tried to start  it on another node only to have 
19:43:31.654705 INFO - loading generated transactions index...
19:43:31.654827 ERROR Failed to init: genesis block mismatch. Probably you set --testnet flag with data dir with non-test blockchain
19:43:31.654923 ERROR Failed to initialize blockchain storage
19:43:31.655020 ERROR Failed to initialize core
@FndNur1Labs @AlbertWerner 
Any one have assistance?

**Comment by SoraKohaku** [comment]
try my repo will work it. but that old libboost~soon will release amajurez
updates~

**Comment by kubator159** [comment]
Hi every one
How could i start a daemon?

**Comment by SoraKohaku** [comment]
pn build/release/src

and try command ./[yourcoind]

see this wiki

https://github.com/FndNur1Labs/CryptonoteEvo/wiki/Issue-And-Solving

On 3/21/18, kubator159 <notifications@github.com> wrote:
> Hi every one
> How could i start a daemon?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/cryptonotefoundation/cryptonote/issues/8#issuecomment-374966642


-- 
Nur1Labs©2013
______________________________
Site Info -> Here <http://nur1labs.com/>

Easy Transaction
MoneyBookers <https://www.moneybookers.com/app/?rid=17274145>

**Comment by Hashflower** [comment]
Hello there i have the same issue.... How to compile the file?? I'm trying cmake with visual Studio but this is hell complicated.... Any ways to build this?? And how?? I think this is the problem many of us has here.
Help appreciated, already spent hours on this (and yes i tried google....) 💃

**Comment by SoraKohaku** [comment]
Credits by homdx

https://github.com/FndNur1Labs/CryptonoteEvo/wiki/Building-Used-Docker%5BHomdx%5D(v2-only)

**Comment by Hashflower** [comment]
Thank you for your reply. So basically i can create my own coin based on this open source code?

**Comment by Hashflower** [comment]
With the previous cryptonote project i managed to start buidling it in a linux Virtual machine but somehow at 11% i got an error and the building cannot finish. Do you have an idea? 

https://ibb.co/dvXXfS

**Comment by SoraKohaku** [comment]
Previous change on v1 all fixed and upgraded to v2 for light supply chain.
See guide video on wiki added last night.

**Comment by Hashflower** [comment]
I went on your wiki but i cannot find any video guide. Trying your project now.

**Comment by SoraKohaku** [comment]
Video guide?did you try new version 2?many fork and we do best serve. As
soon cryptonote platform keep alive.

**Comment by minersbad** [comment]
sorry but how i lunch daemon for ever? i cannot keep open bash linux

**Comment by SoraKohaku** [comment]
Linux as seed. Buy some Amazon vps for public seed.

**Comment by mike2lab** [comment]
hi there. I managed to run the deamon once, then i deleted everything and build again from the begining for a different coin in another folder and i get the same error message when i run the deamon
18:23:44.759699 ERROR Failed to init: genesis block mismatch. Probably you set --testnet flag with data dir with non-test blockchain or another network.
18:23:44.759775 ERROR Failed to initialize blockchain storage
18:23:44.759828 ERROR Failed to initialize core

Is this because i have "127.0.0.1:17236" in my SEED_NODES in the configuraton file?

thanks

**Comment by SoraKohaku** [comment]
What version of your os.

**Comment by mike2lab** [comment]
im on OS X Sierra
i just run the deamOn with the argument --data-dir specifying a folder for the blockchain and it worked but it doesn't connects to my SEED_NODES (127.0.01)

**Comment by SoraKohaku** [comment]
Old script many bug. I think you must change to v2

**Comment by mike2lab** [comment]
Which script u mean ?

**Comment by SoraKohaku** [comment]
Pm me on mail crbru.yuthafiga@gmail.com. busy :)

**Comment by yusufyildiz34** [comment]
The message indicates that the ***genesis block*** is different than the one stored on disk. Try remove contents of the datadir, by default, it is ~/.bitcoin, and try again. For example:
````
rm -rf ~/.monetaverde
````
