### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SoraKohaku** [cryptonotefoundation/cryptonote#91]
2017-Dec-03 10:28:07.441216 WARNING [127.0.0.1:60309 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:09.442524 WARNING [127.0.0.1:34091 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:11.443975 WARNING [127.0.0.1:37061 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:13.445349 WARNING [127.0.0.1:49491 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:15.446863 WARNING [127.0.0.1:34619 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:17.447892 WARNING [127.0.0.1:52749 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:19.449083 WARNING [127.0.0.1:44087 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:21.450109 WARNING [127.0.0.1:45455 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:23.451601 WARNING [127.0.0.1:51849 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:25.452500 WARNING [127.0.0.1:42181 INC] Exception in connectionHandler: TcpConnection::read
2017-Dec-03 10:28:27.453845 WARNING [127.0.0.1:41709 INC] Exception in connectionHandler: TcpConnection::read

**Comment by SoraKohaku** [comment]
VPS fixed

**Comment by agieocean** [comment]
Hi I'm having this same problem (except the ip i have show up is the external ip of the server) how did you fix this?

**Comment by agieocean** [comment]
Possibly helpful, the output of netstat -lntu while running:
```
...
tcp        0     127.0.0.1:18236           0.0.0.0:*               LISTEN
...
tcp        0      0 0.0.0.0:17236           0.0.0.0:*               LISTEN
...
```

**Comment by SoraKohaku** [comment]
the config must have ip not 127.0.0.1 seed undefine will~

**Comment by agieocean** [comment]
Where is this configured? SEED_NODES has my IP, is there another place I have to configure it?
Thank you for the help btw.

**Comment by SoraKohaku** [comment]
you need 2 virtual ip to run it...

**Comment by agieocean** [comment]
Adding a second vps to the configuration, recompiling, and running on both servers stopped the warning, thank you!

**Comment by SoraKohaku** [comment]
close issue hehehe nope....
