### ISSUE TITLE
Erro on connnectivity tool

### ISSUE THREAD

**Issue by SoraKohaku** [cryptonotefoundation/cryptonote#92]
/usr/bin/ld: StreamTools.cpp.o: plugin needed to handle lto object
/tmp/ccQv8vl4.ltrans2.ltrans.o: In function `std::_Function_handler<void (), handle_request_stat(boost::program_options::variables_map&, unsigned long)::{lambda()#2}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.257]':
ccQv8vl4.ltrans2.o:(.text+0x11d3): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
ccQv8vl4.ltrans2.o:(.text+0x1200): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccQv8vl4.ltrans9.ltrans.o: In function `(anonymous namespace)::readVarint(Common::IInputStream&)':
ccQv8vl4.ltrans9.o:(.text+0x223): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
ccQv8vl4.ltrans9.o:(.text+0x259): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
/tmp/ccQv8vl4.ltrans9.ltrans.o: In function `(anonymous namespace)::loadSection(Common::IInputStream&)':
ccQv8vl4.ltrans9.o:(.text+0xb8e): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
ccQv8vl4.ltrans9.o:(.text+0xbe0): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
ccQv8vl4.ltrans9.o:(.text+0xc21): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
ccQv8vl4.ltrans9.o:(.text+0xc4c): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
ccQv8vl4.ltrans9.o:(.text+0xc89): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
/tmp/ccQv8vl4.ltrans9.ltrans.o: In function `(anonymous namespace)::loadValue(Common::IInputStream&, unsigned char)':
ccQv8vl4.ltrans9.o:(.text+0xe4c): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
ccQv8vl4.ltrans9.o:(.text+0xe84): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
ccQv8vl4.ltrans9.o:(.text+0xeac): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
ccQv8vl4.ltrans9.o:(.text+0xed4): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
ccQv8vl4.ltrans9.o:(.text+0xf04): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
/tmp/ccQv8vl4.ltrans9.ltrans.o:ccQv8vl4.ltrans9.o:(.text+0xf24): more undefined references to `Common::read(Common::IInputStream&, void*, unsigned long)' follow
/tmp/ccQv8vl4.ltrans9.ltrans.o: In function `(anonymous namespace)::loadValue(Common::IInputStream&, unsigned char)':
ccQv8vl4.ltrans9.o:(.text+0xffc): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
ccQv8vl4.ltrans9.o:(.text+0x1037): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
ccQv8vl4.ltrans9.o:(.text+0x1096): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
ccQv8vl4.ltrans9.o:(.text+0x10b9): undefined reference to `Common::read(Common::IInputStream&, unsigned char&)'
/tmp/ccQv8vl4.ltrans9.ltrans.o: In function `CryptoNote::KVBinaryInputStreamSerializer::KVBinaryInputStreamSerializer(Common::IInputStream&)':
ccQv8vl4.ltrans9.o:(.text+0x123a): undefined reference to `Common::read(Common::IInputStream&, void*, unsigned long)'
/tmp/ccQv8vl4.ltrans17.ltrans.o: In function `(anonymous namespace)::writeArraySize(Common::IOutputStream&, unsigned long) [clone .lto_priv.136]':
ccQv8vl4.ltrans17.o:(.text+0x251): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
ccQv8vl4.ltrans17.o:(.text+0x27f): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
ccQv8vl4.ltrans17.o:(.text+0x2a3): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
ccQv8vl4.ltrans17.o:(.text+0x2ce): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccQv8vl4.ltrans17.ltrans.o: In function `CryptoNote::KVBinaryOutputStreamSerializer::dump(Common::IOutputStream&)':
ccQv8vl4.ltrans17.o:(.text+0x3ac): undefined reference to `Common::write(Common::IOutputStream&, void const*, unsigned long)'
/tmp/ccQv8vl4.ltrans17.ltrans.o:ccQv8vl4.ltrans17.o:(.text+0x3d3): more undefined references to `Common::write(Common::IOutputStream&, void const*, unsigned long)' follow
collect2: error: ld returned 1 exit status
src/CMakeFiles/ConnectivityTool.dir/build.make:103: recipe for target 'src/connectivity_tool' failed
make[3]: *** [src/connectivity_tool] Error 1
make[3]: Leaving directory '/root/coins/JAVA/build/release'
CMakeFiles/Makefile2:384: recipe for target 'src/CMakeFiles/ConnectivityTool.dir/all' failed
make[2]: *** [src/CMakeFiles/ConnectivityTool.dir/all] Error 2
make[2]: Leaving directory '/root/coins/JAVA/build/release'
Makefile:86: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/coins/JAVA/build/release'
Makefile:20: recipe for target 'build-release' failed
make: *** [build-release] Error 2

**Comment by wizardofzos** [comment]
Same here, trying with a change to src/CMakeLists.txt 

target_link_libraries(ConnectivityTool CryptoNoteCore Logging Crypto P2P Rpc Http Serialization Common System ${Boost_LIBRARIES}) 

(moved the Common to just before System), will post if fixed

**Comment by wizardofzos** [comment]
Can confirm that on Ubuntu 16 the change as mentioned above does result in a working compile....
Now to see if the binaries are functional too :)

**Comment by wizardofzos** [comment]
Also confirming the binary runs ok with the "Genesis Creation"....

![image](https://user-images.githubusercontent.com/117615/33849072-cad86f02-deaf-11e7-96c3-646f12d8f06f.png)

**Comment by SoraKohaku** [comment]
Fixed my own thank +wizard @wizardofzos 

https://github.com/FndNur1Labs/WayangCli

i made costume POS + ICO[from royalties HF] and more on around about GUI

https://github.com/FndNur1Labs/WayangGUI

**Comment by mtheory7** [comment]
Also confirmed that with Ubuntu 16.04 you need to replace the line in src/CMakeLists.txt
with the following:
target_link_libraries(ConnectivityTool CryptoNoteCore Logging Crypto P2P Rpc Http Serialization Common System ${Boost_LIBRARIES})

**Comment by SoraKohaku** [comment]
used gcc7. my repo work

**Comment by gsquaredxc** [comment]
#17

**Comment by superdev810** [comment]
> 
> 
> Same here, trying with a change to src/CMakeLists.txt
> 
> target_link_libraries(ConnectivityTool CryptoNoteCore Logging Crypto P2P Rpc Http Serialization Common System ${Boost_LIBRARIES})
> 
> (moved the Common to just before System), will post if fixed

what's relation that connectivity plugins order?
As you said, after change that plugins order, it's working

**Comment by SoraKohaku** [comment]
I think plugin there too old as libboost already used newer. and as we know for libssl better with libevent. see the last issue of my updates. and that reason changes new platform.

last updates:
https://bitbucket.org/nur1labs/evo-platform/src/master/
