### ISSUE TITLE
unconfirmed transaction if amount >= 11 mio coins

### ISSUE THREAD

**Issue by saloppe73** [cryptonotefoundation/cryptonote#94]
hi

local running a funcoin (almost the "default" settings) at 1 host and 2 vm. all fine until I try to spent >=11 mio coins. all transactions < 11 mio are confirmed - all transactions above are unconfirmed.

any hints?
tnx

**Comment by rainmanp7** [comment]
Are the transactions time released?
Check to see the confirmation time.

**Comment by SoraKohaku** [comment]
see too on block time how much /second before mature~

#thisoldissue xD

**Comment by saloppe73** [comment]
have fix it
